### ISSUE TITLE
Add to Homebrew

### ISSUE THREAD

**Issue by Anahkiasen** [cbednarski/hostess#12]
Could this be made available on Homebrew? Or is it hard to add Go packages there? Would make it easier to install and I could add it to my Brewfile

**Comment by cbednarski** [comment]
Yep! This should be possible. Thanks for opening a ticket.

**Comment by nikolay** [comment]
@cbednarski It's already there, by the way!

**Comment by cbednarski** [comment]
Super, thanks for the tip @nikolay!
