### ISSUE TITLE
HOSTESS_PATH environment variable does not change target file

### ISSUE THREAD

**Issue by CodeShane** [cbednarski/hostess#20]
Specifying the HOSTESS_PATH environment variable does not change hostess' behavior; it still edits /etc/hosts .

To reproduce, set HOSTESS_PATH to point to a different hosts file. execute hostess commands. /etc/hosts is changed instead of the specified file.

**Comment by cbednarski** [comment]
Thanks for the report. This is working for me:

```
$ HOSTESS_PATH=./hosts hostess ls
open ./hosts: no such file or directory
```

Can you show how you're invoking this and tell me which platform you're using?

**Comment by CodeShane** [comment]
Sorry, had failed to export the var, i.e. "export HOSTESS_PATH=file" .. once I did that, it worked as expected. Thank you!

**Comment by cbednarski** [comment]
Glad you got this working! Thanks for following up.
