### ISSUE TITLE
The -n global option has no effect.

### ISSUE THREAD

**Issue by CodeShane** [cbednarski/hostess#21]
The -n global option is supposed to be "no-op. Show changes but don't write them."
Regardless of whether the -n global option is specified, changes are written to /etc/hosts .

**Comment by cbednarski** [comment]
Can you specify the command you ran and what platform you're using?

I don't have exhaustive tests for the frontend but I ran through `add`, `off`, `rm`, and `fix` and `-n` works as expected.

**Comment by cbednarski** [comment]
I think you have the flag between `hostess` and the subcommand.

- `hostess off -n localhost` This works
- `hostess -n off localhost` This does not work

I think the command docs are a big ambiguous here, I'll see if I can get it to work in the other position too.

**Comment by cbednarski** [comment]
This should be fixed in 2f077986f0ed8517fd74b7b422ed688d71fcb625.

**Comment by cbednarski** [comment]
Thanks for reporting this. This should now be fixed in master. I'll put out a release after I've had a chance to look into #20.
