### ISSUE TITLE
Add a `hostess fix --dry-run`

### ISSUE THREAD

**Issue by nikolay** [cbednarski/hostess#24]
Some command error out when the `/etc/hosts` file is invalid (for example, when it has dupes). For scripting purposes, it would be nice to be able to check once in the beginning of a bunch of option and issue a `hostess fix`. The issue is that you can have a `hostess fix`, but it would require a possibly redundant `sudo` access if the configuration is in the expected state.

In the same sense, it would be nice if `apply` also has a `--dry-run` so that you can check before requiring `sudo`.

Imagine a script like this:

```bash
if ! hostess fix --dry-run; then
  sudo hostess fix
fi
if ! hostess apply hostess.json --dry-run; then
  sudo hostess apply hostess.json
fi
```

Of course, there's copy and paste of code, but maybe it could be done somehow via hostess calling itself with `sudo`?

**Comment by cbednarski** [comment]
`-n` is the dry run flag. Can you let me know if this does what you want?

```
$ hostess fix -n
/etc/hosts is already formatted and contains no dupes or conflicts; nothing to do
```

For quieter output you can do:

```
$ hostess fix -n -q
```

**Comment by nikolay** [comment]
@cbednarski Duh! How did I miss that!? Let me try to see if this works as I need it to!

**Comment by cbednarski** [comment]
I may need to change the exit status to 1 if there _would_ be changes. I don't remember what the behavior is here.

**Comment by nikolay** [comment]
@cbednarski You're right! You need to add the exit code as I just tested it, and it always returns `0`!

**Comment by cbednarski** [comment]
The code change to `fix` is small but the UX gets a bit weird because it has unique conditional logic based on `-n` which is inconsistent with other commands. I'm going to add `hostess fixed` exit 0/1/2 to accomplish this.
