### ISSUE TITLE
Add "delip" and "offip" options

### ISSUE THREAD

**Issue by tylert** [cbednarski/hostess#29]
At the moment, there is no nice way to remove/comment out entries in /etc/hosts based on their IP address, only hostnames.  It would be nice to add "delip" and "offip" options to mirror the "del" and "off" options except by IP rather than by host.

For example, if one wanted a quick way to rip out entries like "127.0.1.1 bob", one would normally resort to using "sed" or "grep -v" or some other non-hostess way.  It would be kinda cool to have this functionality all be part of the same tool.

Adding this feature to hostess will allow a single, self-contained binary to do all the interaction with /etc/hosts which might be a nice-to-have feature on container-centric distros like RancherOS, CoreOS, etc. which sometimes don't react well to people poking their /etc/hosts files directly.

**Comment by cbednarski** [comment]
Thanks for the suggestion! I'll have to think about the UX here a bit. For example it probably doesn't make sense to turn off 127.0.0.1, and right now most hostess commands work 1:1 while this would change the interaction to 1:n.

> [this feature] might be a nice-to-have feature on container-centric distros like RancherOS, CoreOS, etc. which sometimes don't react well to people poking their /etc/hosts files directly.

Can you provide some more background here? I haven't used RancherOS or CoreOS so I'm not sure what you mean!

**Comment by tylert** [comment]
I had suggested ```127.0.1.1```, not ```127.0.0.1``` (a single example selected from the many explanations out there http://www.leonardoborda.com/blog/127-0-1-1-ubuntu-debian/).

The choice of using RancherOS or CoreOS isn't terribly important here--the same ```127.0.1.1``` entries get created on Debian and Ubuntu machines too and, thus, copied into any subsequent Docker containers launched there.  Docker seems to treat ```/etc/hosts``` in a *special* way too (for example, https://github.com/docker/docker/issues/2267).

Entries like ```127.0.1.1 6f5d738e``` are less elegant to remove programatically after your hostname gets changed by a later phase/script.  Entries like ```127.0.1.1 bobsfridge\n10.78.0.1 bobsfridge``` may also sometimes be a little sticky for fancy clustering solutions if you don't clean them up.

My particular (peculiar?) immediate use-case will likely involve removing/adding ```10.*.*.*```, ```172.*.*.*``` or ```192.168.*.*``` entries when removing/adding nodes from a cluster managed by a container running on each physical host.

Without looking at the code, it may be possible to allow the UI to just accept a placeholder or wildcard for the host part so you might be able to allow ```delip <dontcare> 127.0.1.1```.

Yes, I realize I should probably rework the horrible host hacking stuff I'm forced to support now and use something better in the future (consul?  avahi?), but, for now, having a tiny, self-contained tool like hostess that I can sprinkle around like confetti is a :cake: :footprints:.

**Comment by cbednarski** [comment]
Yeah makes sense! I run into this too as I use a lot of VMs and the IPs change all the time, so it would be nice to say "oh box is gone, please remove all the hostnames". Thanks for the additional context here. I'm thinking about the different ways to do this... `hostess find -ip 127.0.0.1 | hostess rm -` or `hostess del -ip` or `hostess delip` or something like that. I have been thinking of adding find but it seems a bit awkward in this case.

There are already quite a few commands so I'm thinking whether a flag or new specialized command or generic command (e.g. find) makes the most sense. Thanks again for the feedback!

**Comment by tylert** [comment]
Nice!  The ```hostess find -ip $IP | hostess rm -``` would be my pick.

Maybe some kind of JSON blob for ```hostess rm myblob.json``` (in the off chance that folks want to skip piping ```hostess find```) that looks a bit like:
```
{
  "domain": "*",
  "ip": "172.16.0.56",
  "removed": true
}
```
