### ISSUE TITLE
Released binary are different

### ISSUE THREAD

**Issue by kenchan0130** [cbednarski/hostess#30]
It seems that this tool binary of [v0.2.0](https://github.com/cbednarski/hostess/releases/tag/v0.2.0) are different.

I downloaded

- https://github.com/cbednarski/hostess/releases/download/v0.2.0/hostess_darwin_386
- https://github.com/cbednarski/hostess/releases/download/v0.2.0/hostess_darwin_amd64

these binary.

And I execute them,  the help message appeared as follows:

```
NAME:
   hostess - an idempotent tool for managing /etc/hosts

 * Commands will exit 0 or 1 in a sensible way to facilitate scripting.
 * Hostess operates on /etc/hosts by default. Specify the HOSTESS_PATH
   environment variable to change this.
 * Run 'hostess fix -n' to preview changes hostess will make to your hostsfile.
 * Report bugs and feedback at https://github.com/cbednarski/hostess

USAGE:
   hostess_darwin_amd64 [global options] command [command options] [arguments...]

VERSION:
   0.1.0

AUTHOR(S):
   Chris Bednarski <banzaimonkey@gmail.com>

COMMANDS:
    add		add or replace a hosts entry
    aff		add or replace a hosts entry in an off state
    del		delete a hosts entry
    has		exit 0 if entry exists, 1 if not
    on		enable a hosts entry (if if exists)
    off		disable a hosts entry (don't delete it)
    list	list entries in the hosts file
    fix		reformat the hosts file based on hostess' rules
    dump	dump the hosts file as JSON
    apply	add hostnames from a JSON file to the hosts file

GLOBAL OPTIONS:
   -f			operate even if there are errors or conflicts
   -n			no-op. Show changes but don't write them.
   -q			quiet operation -- no notices
   -s			silent operation -- no errors (implies -q)
   --help, -h		show help
   --version, -v	print the version
```

It seems that this binary version is `0.1.0`. I expected that `0.2.0` will be output in version section.

**Comment by cbednarski** [comment]
Hi there, you're right! Sorry about that. I goofed when I did the 0.2.0 build. The build is based on the tag but I did not correctly update the version in the source file. I believe the [latest release](https://github.com/cbednarski/hostess/releases/tag/v0.3.0) is correct now. Please let me know if you run into any other problems!
