### ISSUE TITLE
Can't find package

### ISSUE THREAD

**Issue by juslintek** [cbednarski/hostess#34]
Ubuntu 18.10
```
~/hostess$ make
go get github.com/golang/lint/golint
go get github.com/stretchr/testify/assert
go get golang.org/x/tools/cmd/cover
go get
go build cmd/hostess/hostess.go
cmd/hostess/hostess.go:6:2: cannot find package "github.com/cbednarski/hostess" in any of:
	/snap/go/3129/src/github.com/cbednarski/hostess (from $GOROOT)
	gocode/src/github.com/cbednarski/hostess (from $GOPATH)
make: *** [Makefile:20: build] Error 1
```

**Comment by cbednarski** [comment]
Looks like there is something wrong with your GOPATH, and as such the go build tool cannot locate the package. See the [install docs](https://golang.org/doc/install) for more info.

```
$ go env | grep GOPATH
GOPATH="/home/username/go"
$ pwd
/home/username/go/src/github.com/cbednarski/hostess
```

If you download the project with `go get` it should end up in the right place. However, if you are using `go` installed via `snap` there may be some other permission issue that you need to work out. For example, the `go` binary in the snap may not be allowed to read or traverse your home directory.
