### ISSUE TITLE
Outdated package manager convention

### ISSUE THREAD

**Issue by MateuszKubuszok** [cbednarski/hostess#35]
When I was installing `hostess` on Arch Linux I've got an error.

The error (and solution) are linked in this ticket: https://github.com/golang/lint/issues/415.

I had to use `find . -type f -exec sed -i 's/github.com\/golang/golang.org\/x/g' {} \;` to fix this issue, but it would make more sense to update this in repository.

**Comment by cbednarski** [comment]
Thanks for the report. I've updated the makefile to reflect the correct import path. Cheers!
