### ISSUE TITLE
fmt does not actually fix dupes as stated

### ISSUE THREAD

**Issue by jtrinklein** [cbednarski/hostess#39]
OS: macOS - all versions affected (tested on 10.13, 10.14 and 10.15)
hostess version: 0.5.0

Given this hosts file:

```
127.0.0.1 localhost kubernetes.docker.internal
::1 localhost
# Added by Docker Desktop
# To allow the same kube context to work on the host and the container:
127.0.0.1 kubernetes.docker.internal
# End of section
```

I would expect running the fmt command to remove duplicates and format the file correctly. However, running hostess fmt results in the following error:

```
$ sudo hostess fmt
duplicate hostname entry for kubernetes.docker.internal -> 127.0.0.1
Errors while parsing hostsfile. Please fix any dupes or conflicts and try again.
```

**Comment by cbednarski** [comment]
Thanks for the report. This is fixed! A release is pending.
