### ISSUE TITLE
set-hostname command

### ISSUE THREAD

**Issue by cbednarski** [cbednarski/hostess#6]
Wrap ubuntu's hostnamectl command AND write the localhost entry at the same time. Useful for e.g. AWS instances that have sudo lag because hostname isn't set.

    hostnamectl set-hostname NAME

- Calling with 1 arg will set the hostname
- Calling with 0 args will try to fix the hostname (e.g. detect hostname and write to `/etc/hosts`)

**Comment by passcod** [comment]
Hostnamectl is also available to Systemd distros, not only Ubuntu. Also would be nice to have hostess handle OS X's hostname utility.

**Comment by cbednarski** [comment]
@passcod Thanks for the info regarding hostnamectl on systemd! That will make standardizing this quite a bit easier.

Setting via `hostname` does not persist across reboots, but I just did some digging on hostname on OSX and found there's a similar mechanism to make the change persistent. From `man hostname`:

> To keep the hostname between reboots, run `scutil --set HostName name-of-host'.

There are is one outstanding issue on OSX that is blocking a release but since the hostnamectl functionality is fairly well-described I'll work on this soon. Thanks for the feedback!

**Comment by cbednarski** [comment]
I've reconsidered this, and since hostnamectl is already available and I would only be wrapping the command, I don't think there's much point. Since the set-hostname feature is mostly useful for servers I don't see a lot of value in making this work for OSX, and it seems most current / future linux systems will already have this feature.

I'm closing this but if you have a strong use-case I will reconsider it.
